name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install depo
      run: sudo apt install wget make gawk gcc bc bison flex xorriso libelf-dev libssl-dev -y
    
    - name: List folder
      run:  ls -l 

    - name: Change folder
      run: |
          cd src/ 
          ls -l

    - name: List folder
      run:  ls -l       
        
    - name: Change mode
      run: chmod +x build_minimal_linux_live.sh
    
    - name: Build
      run: ./build_minimal_linux_live.sh
    
    - name: Upload asset to release
      uses: actions-github/upload-to-release@v1.0.0
      with:
       file: mll_image.tgz
       type: application/gzip
    
    - name: Upload asset to release
      uses: actions-github/upload-to-release@v1.0.0
      with:
       file: minimal_linux_live.iso
       type: application/octet-stream
